### ISSUE TITLE
GCC 4.8 halts compilation

### ISSUE THREAD

**Issue by LillyWho** [nougat-hammerhead/kernel_lge_hammerhead#1]
Using GCC 4.8 arm eabi from the AOSP repo, every time I try to compile, I get this:

`Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at kernel/timeconst.pl line 373.
/home/alexander/android/cm14/kernel/lge/hammerhead/kernel/Makefile:129: recipe for target 'kernel/timeconst.h' failed
make[1]: *** [kernel/timeconst.h] Error 255
`
I can only presume there are some build flags missing or something along those lines, because the file hasn't been changed. Host OS is Ubuntu 16.10

**Comment by yashade** [comment]
hmm i build it on ubuntu 14.04 not 16.10. maybe you need some extra packages...

**Comment by LillyWho** [comment]
Any packages that are stereotypically missing on newer Ubuntu releases? I've got everything needed for building Android.

**Comment by yashade** [comment]
sudo apt-get update

sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip

**Comment by LillyWho** [comment]
Everything installed and upt to date already.

**Comment by yashade** [comment]
do you have gnu bc?

**Comment by LillyWho** [comment]
Installed and up to date.

**Comment by yashade** [comment]
have no idea lol. i can compile it.

**Comment by LillyWho** [comment]
Something I found: http://linux-kernel.2935.n7.nabble.com/PATCH-1-5-kbuild-remove-deprecated-use-of-defined-in-timeconst-pl-td556009.html
Will try this patch and report back.

**Comment by LillyWho** [comment]
It did compile, however I am unsure whether it is bootable or not.
